# This tells Netlify where to find the function.
[functions]
  directory = "netlify/functions/"

# This plugin automatically finds your function's package.json
# and installs its dependencies during the build.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
